- apps/expo/src/lang/en.json
- apps/expo/src/lang/nl.json
Release a new version with fixed CO₂ spelling.
> Fix CO₂ spelling

- apps/expo/src/screens/info/InfoScreen.tsx
This PR changes the links that are on the Info page.
> feat: update links

- apps/expo/android/gradle.properties
Changed the API-level to 33 to target android 13.
> build: Changed the API-level to 33

- apps/expo/ios/Podfile.lock
- docs/ios.md
This pull request updates the Markdown documentation for iOS. It also fixes the Podfile.lock so the expo build doesn't fail.
-
-
> Fixing iOS build process on MacOS

- apps/expo/src/screens/DeviceOverviewScreen/_listItem.tsx
- apps/expo/src/screens/MeasurementsScreen/index.tsx
- apps/expo/src/types/env.d.ts
- yarn.lock
When checking this PR you have to add this line to the .env file: 
MANUAL_URL="https://manuals.tst.energietransitiewindesheim.nl/devices/"
> fix: Dynamic name in list

- apps/expo/src/components/common/bottomSheets/DeviceBottomSheet.tsx
- apps/expo/src/constants.ts
- apps/expo/src/hooks/device/useDeviceType.tsx
- apps/expo/src/screens/MeasurementsScreen/index.tsx
- apps/expo/src/screens/home/AddDeviceScreen.tsx
- apps/expo/src/screens/home/AddOnlineDataSourceScreen.tsx
- apps/expo/src/screens/home/ConnectScreen.tsx
- apps/expo/src/screens/home/DeviceOverviewScreen/_listItem.tsx
- apps/expo/src/screens/home/ProvisionScreen.tsx
- apps/expo/src/screens/home/SearchDeviceScreen.tsx
- apps/expo/src/screens/home/WifiOverviewScreen/index.tsx
- apps/expo/src/screens/settings/ExternalProviderScreen/_externalProviderListItem.tsx
- apps/expo/src/screens/settings/SettingsScreen/index.tsx
- apps/expo/src/types/env.d.ts
- apps/expo/src/types/navigation.ts
<!-- DO NOT IGNORE THE TEMPLATE!
Changed the device names on measurement screen to more user-friendly names
> Fix-changed the device names on measurement screen

- yarn.lock
In 82e898e21dd36cafb9d55e14b3cb3de46630ea82 I updated a dependency, but I forgot to update/include the lockfile in the commit.
> build: update lockfile

- apps/expo/src/screens/MeasurementsScreen/index.tsx
Remove building information from measurement screen
No linked issues
> refactor: remove building information from measurement screen

- apps/expo/package.json
- apps/expo/src/screens/home/AddOnlineDataSourceScreen.tsx
- apps/expo/src/screens/home/DeviceOverviewScreen/_listItem.tsx
- yarn.lock
- Enelogic is now available in the device list.
- When Enelogic is connected, the user is automatically directed to the device screen.
> fix: Enelogic is now available in the device list

- apps/expo/src/screens/info/InfoScreen.tsx
- apps/expo/src/types/api.ts
The link for the FAQ page gets pulled from the API, depending on the campaign the user is in.
No linked issues
> fix: get app links from api

- apps/expo/src/screens/info/InfoScreen.tsx
Added language based header for FAQ manual and About manual in info page
> added - language header for FAQ manual and About manual

- apps/expo/CHANGELOG.md
- apps/expo/android/app/build.gradle
- apps/expo/app.json
- apps/expo/ios/NeedforHeat.xcodeproj/project.pbxproj
- apps/expo/ios/NeedforHeat/Info.plist
- apps/expo/package.json
> Sync main with dev

- apps/expo/src/screens/info/InfoScreen.tsx
fixed FAQ url not working for uninvited users using the app.
> FAQ url not working for uninvited users using the app.

- apps/expo/src/screens/home/DeviceOverviewScreen/circleMenu.tsx
fixed overlap deviceList text with circle menu
> Overlap deviceList text with circle menu

- apps/expo/src/screens/home/DeviceOverviewScreen/_deviceList.tsx
- apps/expo/src/screens/home/DeviceOverviewScreen/index.tsx
fix: deviceList 'no data received' not updating on Homepage when user navigates from ProvisionScreen to HomeScreen
> No data received for device when new device is added

- apps/expo/src/screens/info/InfoScreen.tsx
fix: privacy policy language header
> privacy policy language header

- apps/expo/CHANGELOG.md
- apps/expo/android/app/build.gradle
- apps/expo/app.json
- apps/expo/ios/NeedforHeat.xcodeproj/project.pbxproj
- apps/expo/ios/NeedforHeat/Info.plist
- apps/expo/package.json
> Merge main in dev

- apps/expo/src/screens/info/InfoScreen.tsx
fix: possibility that resolvedLanguage is undefined
> fixed possibility that resolvedLanguage is undefined

- apps/expo/src/constants.ts
- apps/expo/src/screens/info/InfoScreen.tsx
Change all hard-coded links in the app to target our production environment.
@NormalNickYT can you guys check if this is sufficient/correct on the app code side? 
I will also be changing the NFH_API_URL environment variable in GitHub Actions to also target the production API.
> feat: target production manual links

- apps/expo/src/constants.ts
- apps/expo/src/screens/info/InfoScreen.tsx
Target production environment.
> Production

- .expo/packager-info.json
- .expo/settings.json
- .vscode/settings.json
- apps/expo/src/components/common/bottomSheets/DeviceBottomSheet.tsx
- apps/expo/src/components/common/bottomSheets/PropertyBottomSheet.tsx
- apps/expo/src/lang/en-US.json
- apps/expo/src/lang/nl-NL.json
- apps/expo/src/screens/MeasurementsScreen/_deviceGraph.tsx
- apps/expo/src/screens/MeasurementsScreen/index.tsx
- apps/expo/src/screens/home/DeviceOverviewScreen/_listItem.tsx
- apps/expo/src/screens/home/WifiOverviewScreen/index.tsx
- apps/expo/src/utils/tools.ts
- apps/expo/tsconfig.json
- tsconfig.json
Improved style in measurementsScreen & Devices. Also improved property selection with translation.
Fix that if there is an open Wi-Fi that needs connecting to. It no longer ask for a password.
https://github.com/Labhatorian/NeedForHeat-GearUp-ProjectIssues/issues/98
--
> Feat/measurements improve property selection & fix open network

- .github/workflows/eas-build.yml
Attempt to fix workflow and semantics
> Fix workflow and semantics

- .github/workflows/semantic-release.yml
> v3.1.0 third try

- apps/expo/ios/NeedforHeat.xcodeproj/project.pbxproj
Try to fix an error that's confusing
> v3.1.0 fifth try

- apps/expo/android/app/build.gradle
Android crashes for some reason
> Fix: improved handlign of the envfile

- apps/expo/ios/InfoPlist.xcstrings
- apps/expo/ios/NeedforHeat.xcodeproj/project.pbxproj
Adds translations to PList on request.
> PList Translations
